default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: rubiti
  password: 12345678
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test